apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: result-app
    image: kodekloud/examplevotingapp_result:v1
    ports:
    - containerPort: 80

# result app use this piece of code
# the result app tries to access postgresql via this the name db

#  var pool = new pg.Pool({connectionString: 'postgres://postgres:postgre@db/postgres' }); 
