apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: voting-app
    image: kodekloud/examplevotingapp_vote:v1
    ports:
    - containerPort: 80

# the python frontend web app has this piece of code
# app = Flask(__name__)
# def get_redis():
#   if not hasattr(g, 'redis'):
#      g.redis = Redisfhost="redis"1 db=0, socket_timeout=5) 
#   return g.redis 


# the voting app try to access another pod using the name redis